### ISSUE TITLE
hasCJKLanguage missing

### ISSUE THREAD

**Issue by dim0627** [zzzmisa/zzzmisa.github.io#1]
こないだはPRありがとうございました！
ちらっとレポジトリ見てたら使ってもらってるサイトがあったので覗いちゃいました。

以下のCJK用設定をconfig.tomlにされてないようなので、してみると良いかもしれません。一覧の{{ .Summary }}が貫通しなくなります。
https://gohugo.io/content-management/summaries/#hugo-defined-automatic-summary-splitting
参考
https://github.com/dim0627/blog/blob/master/config.toml#L7

このissueは閉じちゃってOKです。

**Comment by zzzmisa** [comment]
アドバイスありがとうございます！
早速反映させました。
